# This is useless -- but want want to define some definitive routes for the bundle
piairre.skuse.routes:
  resource:
    path: '@PiairreSkuseBundle/src/Controller/'
    namespace: Piairre\Skuse\Controller
  type: attribute
  prefix: piairre_skuse