services:
  _defaults:
    autowire: true
    autoconfigure: true

  Piairre\Skuse\Controller\DocumentationController:
    arguments:
      $openApiUrl: '%piairre_skuse.open_api_url%'
      $theme: '%piairre_skuse.theme%'
    tags:
      - { name: controller.service_arguments }
