parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Generator
  Piairre\Skuse\Generator\OpenApiGenerator: ~

  # Controller
  Piairre\Skuse\Controller\DocumentationController: ~